# Beta -> (β)
# Sigma -> (σ)
# summation -> (Σ)
# Derivative -> (∂)
# learning rate -> (η)
# y_hat -> (ŷ)
# y_bar -> (ȳ)
# x_bar -> (x̄)
# x_inverse -> (x⁻¹)
# x_transpose -> (xᵀ)
# x_squared -> (x²)
# unequal to -> (≠)
# Lambda -> (λ)
# theta -> (θ)
# epsilon -> (ε₀)